### ISSUE TITLE
Mystic scrolls not dropping mobs in Ter Mur or Stygian Abyss Dungeon

### ISSUE THREAD

**Issue by Icenerox23** [ageofbritannia/AOBUODevelopment-and-BugReporter#14]
Multiple sources say that the mystic scrolls should be dropping from, putrid gargoyles at the start of the tomb of kings, lava elementals around Ter Mur and Stygian Abyss dungeon and the champ bosses in Stygian Abyss Dungeon/Ter Mur. However, as of playing and farming lava elementals and putrid gargoyles not a single mystic scroll had dropped, instead only normal magery scrolls had been dropping. The sources for where these scrolls drop here:
https://www.uoguide.com/Mysticism
https://community.stratics.com/threads/mysticism-scrolls.156305/
https://community.stratics.com/threads/mysticism-spells.158984/
https://community.stratics.com/threads/5th-circle-mysticism-spell.159259/

**Comment by ageofbritannia** [comment]
This issue is also across other servers however we are going to look to add these in the near future!

**Comment by ageofbritannia** [comment]
Ok so, sorry for the delay in getting this one down! 
Thanks to @Kyle for supporting us fix this issue. 

@Icenerox23 Thanks so much for reporting! 

We have investigated and found several mobs were missing the scroll drop references this has been fixed see the below list!

- Lava Elemental
- Putrid Undead Gargoyle
- Primeval Lich
- Fire Daemon
- Skeletal Lich
- Medusa
